# Ports to expose
tasks:
  - init: |
      nvm install 22
      nvm alias default 22
    command: ./dev.sh
    openMode: split-right

ports:
  - port: 3333
    visibility: public
    onOpen: open-preview
